//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPhoneApi.HhaExchange2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://www.hhaexchange.com/apis/hhaws.search", ConfigurationName="HhaExchange2.SearchAPISoap")]
    public interface SearchAPISoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.hhaexchange.com/apis/hhaws.search/GetCallerDataByCallerID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResponse))]
        WebPhoneApi.HhaExchange2.CallerIDLookupResponse GetCallerDataByCallerID(string appName, string appSecret, string appKey, string callerId, string filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.hhaexchange.com/apis/hhaws.search/GetCallerDataByCallerID", ReplyAction="*")]
        System.Threading.Tasks.Task<WebPhoneApi.HhaExchange2.CallerIDLookupResponse> GetCallerDataByCallerIDAsync(string appName, string appSecret, string appKey, string callerId, string filter);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.hhaexchange.com/apis/hhaws.search")]
    public partial class CallerIDLookupResponse : BaseResponse {
        
        private Item[] lookupDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Item[] LookupData {
            get {
                return this.lookupDataField;
            }
            set {
                this.lookupDataField = value;
                this.RaisePropertyChanged("LookupData");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.hhaexchange.com/apis/hhaws.search")]
    public partial class Item : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeField;
        
        private string coordinator1Field;
        
        private string coordinator2Field;
        
        private string coordinator3Field;
        
        private string[] servicesField;
        
        private string primaryContractField;
        
        private string branchField;
        
        private string teamField;
        
        private string locationField;
        
        private string primaryLanguageField;
        
        private string zipField;
        
        private string stateField;
        
        private string cityField;
        
        private string nurseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Coordinator1 {
            get {
                return this.coordinator1Field;
            }
            set {
                this.coordinator1Field = value;
                this.RaisePropertyChanged("Coordinator1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Coordinator2 {
            get {
                return this.coordinator2Field;
            }
            set {
                this.coordinator2Field = value;
                this.RaisePropertyChanged("Coordinator2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Coordinator3 {
            get {
                return this.coordinator3Field;
            }
            set {
                this.coordinator3Field = value;
                this.RaisePropertyChanged("Coordinator3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Service")]
        public string[] Services {
            get {
                return this.servicesField;
            }
            set {
                this.servicesField = value;
                this.RaisePropertyChanged("Services");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string PrimaryContract {
            get {
                return this.primaryContractField;
            }
            set {
                this.primaryContractField = value;
                this.RaisePropertyChanged("PrimaryContract");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Branch {
            get {
                return this.branchField;
            }
            set {
                this.branchField = value;
                this.RaisePropertyChanged("Branch");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Team {
            get {
                return this.teamField;
            }
            set {
                this.teamField = value;
                this.RaisePropertyChanged("Team");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("Location");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string PrimaryLanguage {
            get {
                return this.primaryLanguageField;
            }
            set {
                this.primaryLanguageField = value;
                this.RaisePropertyChanged("PrimaryLanguage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
                this.RaisePropertyChanged("Zip");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Nurse {
            get {
                return this.nurseField;
            }
            set {
                this.nurseField = value;
                this.RaisePropertyChanged("Nurse");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.hhaexchange.com/apis/hhaws.search")]
    public partial class ErrorInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int errorIDField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ErrorID {
            get {
                return this.errorIDField;
            }
            set {
                this.errorIDField = value;
                this.RaisePropertyChanged("ErrorID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("ErrorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.hhaexchange.com/apis/hhaws.search")]
    public partial class Result : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ErrorInfo errorInfoField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ErrorInfo ErrorInfo {
            get {
                return this.errorInfoField;
            }
            set {
                this.errorInfoField = value;
                this.RaisePropertyChanged("ErrorInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CallerIDLookupResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.hhaexchange.com/apis/hhaws.search")]
    public abstract partial class BaseResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Result resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Result Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SearchAPISoapChannel : WebPhoneApi.HhaExchange2.SearchAPISoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SearchAPISoapClient : System.ServiceModel.ClientBase<WebPhoneApi.HhaExchange2.SearchAPISoap>, WebPhoneApi.HhaExchange2.SearchAPISoap {
        
        public SearchAPISoapClient() {
        }
        
        public SearchAPISoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SearchAPISoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchAPISoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchAPISoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebPhoneApi.HhaExchange2.CallerIDLookupResponse GetCallerDataByCallerID(string appName, string appSecret, string appKey, string callerId, string filter) {
            return base.Channel.GetCallerDataByCallerID(appName, appSecret, appKey, callerId, filter);
        }
        
        public System.Threading.Tasks.Task<WebPhoneApi.HhaExchange2.CallerIDLookupResponse> GetCallerDataByCallerIDAsync(string appName, string appSecret, string appKey, string callerId, string filter) {
            return base.Channel.GetCallerDataByCallerIDAsync(appName, appSecret, appKey, callerId, filter);
        }
    }
}
