//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public long Id { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public string OriginalValue { get; set; }
        public string NewValue { get; set; }
        public Nullable<int> RecordId { get; set; }
        public string EventType { get; set; }
        public string Model { get; set; }
    
        public virtual User User { get; set; }
    }
}
