//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfficeLocation
    {
        public int Id { get; set; }
        public string Dns { get; set; }
        public string Address { get; set; }
        public string Comment { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public bool IsDeleted { get; set; }
        public string RouterDetails { get; set; }
        public string ServerDetails { get; set; }
        public string IspDetails { get; set; }
        public string GeneralNotes { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
