//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Server
    {
        public int Id { get; set; }
        public string IpAddress { get; set; }
        public string AdminUserName { get; set; }
        public string Password { get; set; }
        public bool IsDeleted { get; set; }
    }
}
