//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToDo
    {
        public int Id { get; set; }
        public string Task { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> CastomerId { get; set; }
        public Nullable<bool> IsDone { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> PriorityId { get; set; }
        public Nullable<long> UserId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Priority Priority { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
    }
}
